### PR TITLE
Change/machine-precision_quats

### PR DESCRIPTION
**Pull request by Gbowker**

### CODE REVIEW

**Comment by aplowman** [comment]
Can you confirm this fixes your problem with inconsistent orientations reported by DAMASK? Regarding your example in https://github.com/LightForm-group/damask-parse/issues/7#issuecomment-822246047, I'm not sure I understand how adding a bunch of zeros should change anything - those numbers are obviously the same! Or is this a problem with how DAMASK parses the YAML file (in which case we should fix it in DAMASK)?

Currently, the orientations seem to have around 15 decimal places in `material.yaml`. Where there are fewer digits is most likely because the number can be represented with the same precision using fewer digits, i.e. it has some zeros at the end. If ~15 decimal places is not good enough, then I think we might have to adopt an arbitrary precision format like `Decimal`. On my machine, this is reported as the precision limit of `np.double`:

```
print(np.finfo(np.double).precision)
>>> 15
```

...so asking Python for more decimal places doesn't do anything meaningful, and I think "rounding" to 30 d.p. the orientations in `get_HDF5_incremental_quantity` wouldn't help.

Perhaps @pshanthraj or @mikesmic could offer their thoughts.

**Comment by mikesmic** [comment]
I've just had a look at the source and the error comes from checking the quaternion is unit magnitude:
```
  if (dNeq(norm2(qu),1.0_pReal)) &
    call IO_error(402,ext_msg='fromQuaternion')
```
and pReal is set as
`  integer,     parameter :: pReal      = IEEE_selected_real_kind(15,307)                            !< number with 15 significant digits, up to 1e+-307 (typically 64 bit)`.
So I think np.double should be enough but it'll need to be written to the file at full precision and have been normalised to be unit magnitude at some point.

**Comment by aplowman** [comment]
Thanks @mikesmic . So we just need to figure out how to ensure 15 decimal places are written out for floats when dumping to YAML, [here](https://github.com/LightForm-group/damask-parse/blob/2a08ffda8b23fe2e36189fe5827611267483351c/damask_parse/writers.py#L325).

**Comment by Gbowker** [comment]
Thanks both. Ive found the initial reason I wanted to ensure the accuracy was not in fact caused by this, but by a different error on my part. Apologies for the trouble, but do you think its still worth ensuring that the components be written with a consistent number of characters rather than omitting zeros? Thanks

**Pull request closed without merging**
